name: Python CI

on:
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Скачиваем код
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Ставим Python (в ruff.toml указан target-version = "py312", ставим 3.12)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # 3. Ставим зависимости из вашего requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Запускаем Ruff
    # Используем конфиг ruff.toml, который лежит в корне, и проверяем папку src/
    - name: Run Ruff
      uses: astral-sh/ruff-action@v3
      with:
        args: "check --config=ruff.toml ./src/"

    # 5. Запускаем тесты
    # Pytest сам найдет тесты в папке src
    - name: Run Pytest
      run: pytest
